wechat:
  my-app-id: wx4d4eec06d12c0137
  my-app-secret: 76c1b4d54396e3ab284a3d5d1c7037d9

jwt:
  header: Authorization
  secret: 18231926271
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/imloves?characterEncoding=utf-8

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080